AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "fraudmini: Stage 0.1 minimal API"

Globals:
  Function:
    Runtime: python3.11
    Timeout: 5
    MemorySize: 256

Resources:
  AppDataKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS CMK for fraudmini data
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  AppDataKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/fraudmini-appdata
      TargetKeyId: !Ref AppDataKey

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: fraudmini-api
      StageName: prod
      EndpointConfiguration: REGIONAL

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fraudmini-health
      CodeUri: src/health/
      Handler: app.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /health
            Method: GET

Outputs:
  ApiUrl:
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod
