AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "fraudmini: Stage 0.1 minimal API"

Globals:
  Function:
    Runtime: python3.11
    Timeout: 5
    MemorySize: 256

Resources:
  AppDataKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS CMK for fraudmini data
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  AppDataKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/fraudmini-appdata
      TargetKeyId: !Ref AppDataKey

  RawEventsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub fraudmini-raw-events-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref AppDataKey

  RawEventsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RawEventsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${RawEventsBucket}
              - !Sub arn:aws:s3:::${RawEventsBucket}/*
            Condition:
              Bool: { "aws:SecureTransport": "false" }
          - Sid: EnforceKMSEncryptionOnPut
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub arn:aws:s3:::${RawEventsBucket}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: fraudmini-api
      StageName: prod
      EndpointConfiguration: REGIONAL

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fraudmini-health
      CodeUri: src/health/
      Handler: app.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /health
            Method: GET

Outputs:
  ApiUrl:
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod
