AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "fraudmini: Stage 0.1 minimal API"

Globals:
  Function:
    Runtime: python3.11
    Timeout: 5
    MemorySize: 256

Resources:
  AppDataKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS CMK for fraudmini data
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  AppDataKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/fraudmini-appdata
      TargetKeyId: !Ref AppDataKey

  RawEventsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub fraudmini-raw-events-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref AppDataKey

  RawEventsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RawEventsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${RawEventsBucket}
              - !Sub arn:aws:s3:::${RawEventsBucket}/*
            Condition:
              Bool: { "aws:SecureTransport": "false" }
          - Sid: EnforceKMSEncryptionOnPut
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub arn:aws:s3:::${RawEventsBucket}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"
  AppLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub fraudmini-applogs-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref AppDataKey

  AppLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${AppLogsBucket}
              - !Sub arn:aws:s3:::${AppLogsBucket}/*
            Condition:
              Bool: { "aws:SecureTransport": "false" }
          - Sid: EnforceKMSEncryptionOnPut
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub arn:aws:s3:::${AppLogsBucket}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"

  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub fraudmini-cloudtrail-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${CloudTrailBucket}

          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${CloudTrailBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${CloudTrailBucket}
              - !Sub arn:aws:s3:::${CloudTrailBucket}/*
            Condition:
              Bool:
                aws:SecureTransport: "false"

  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      IsLogging: true
      S3BucketName: !Ref CloudTrailBucket
      TrailName: fraudmini-trail
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: false
      EnableLogFileValidation: true

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: fraudmini-api
      StageName: prod
      EndpointConfiguration: REGIONAL

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fraudmini-health
      CodeUri: src/health/
      Handler: app.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /health
            Method: GET

Outputs:
  ApiUrl:
    Description: API base URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod
  RawEventsBucketName:
    Description: Raw events bucket
    Value: !Ref RawEventsBucket
  AppLogsBucketName:
    Description: App logs bucket
    Value: !Ref AppLogsBucket
  AppDataKmsKeyArn:
    Description: KMS key ARN
    Value: !GetAtt AppDataKey.Arn
