openapi: 3.0.1
info:
  title: fraudmini API
  version: "1.0.0"

x-amazon-apigateway-request-validators:
  body-only:
    validateRequestBody: true
    validateRequestParameters: false

paths:
  /score:
    post:
      summary: Score a transaction (schema-only)
      x-amazon-apigateway-request-validator: body-only
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "501":
          description: Not implemented
        "400":
          description: Bad Request - validation failed
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {"statusCode": 501}
        responses:
          default:
            statusCode: "501"

components:
  schemas:
    Transaction:
      type: object
      required:
        - transaction_id
        - user_id
        - amount
        - currency
        - merchant_id
        - channel
        - ts
        - ip
        - country
        - device_id
        - card_bin
        - card_last4
        - attempts_last_10min
      properties:
        transaction_id: { type: string, minLength: 4, maxLength: 64 }
        user_id: { type: string, minLength: 1, maxLength: 64 }
        amount: { type: number, minimum: 0 }
        currency: { type: string, pattern: "^[A-Z]{3}$" }
        merchant_id: { type: string, minLength: 1, maxLength: 64 }
        channel:
          {
            type: string,
            enum: [card_not_present, card_present, bank_transfer],
          }
        ts: { type: string, format: date-time }
        ip: { type: string, format: ipv4 }
        country: { type: string, minLength: 2, maxLength: 2 }
        device_id: { type: string, minLength: 1, maxLength: 64 }
        card_bin: { type: string, pattern: "^[0-9]{6,8}$" }
        card_last4: { type: string, pattern: "^[0-9]{4}$" }
        attempts_last_10min: { type: integer, minimum: 0, maximum: 100 }
      additionalProperties: false
